BSMWeb/Models/AuditLog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogId { get; set; }
        public string ReviewerName { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string ActionTaken { get; set; }
        public string Comments { get; set; }
    }
}

BSMWeb/Controllers/AuditLogsController.cs
using System.Configuration;
using System.Data;
using System.Net;
using System.Web.Mvc;
using BSMDataAccess;
using BSMWeb.Models;

[MemberAuthorize(new UserType[] { UserType.BSMADMIN })]
public class AuditLogsController : Controller
{
	private string _connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;

	private BSMEntities db = new BSMEntities();

	[HttpGet]
	public ActionResult Index()
	{
		string reviewerName = null;
		string auditDate = null;
		DataSet dataSet = DataViewer.GetReviewSheet(_connectionString, reviewerName, auditDate);
		return View(dataSet);
	}

	[HttpPost]
	public ActionResult Index(string auditDate, string reviewerName)
	{
		string _auditDate = null;
		string _reviewerName = null;
		if (auditDate != "")
		{
			_auditDate = auditDate;
		}
		if (reviewerName != "")
		{
			_reviewerName = reviewerName;
		}
		DataSet dataSet = DataViewer.GetReviewSheet(_connectionString, _reviewerName, _auditDate);
		return View(dataSet);
	}

	public ActionResult Details(int? id)
	{
		if (!id.HasValue)
		{
			return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		}
		AuditLog auditLog = db.AuditLogs.Find(id);
		if (auditLog == null)
		{
			return HttpNotFound();
		}
		return View(auditLog);
	}

	public ActionResult Create()
	{
		return View();
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public ActionResult Create([Bind(Include = "AuditLogId,ReviewerName,AuditDate,ActionTaken,Comments")] AuditLog auditLog)
	{
		if (base.ModelState.IsValid)
		{
			db.AuditLogs.Add(auditLog);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
		return View(auditLog);
	}

	public ActionResult Edit(int? id)
	{
		if (!id.HasValue)
		{
			return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		}
		AuditLog auditLog = db.AuditLogs.Find(id);
		if (auditLog == null)
		{
			return HttpNotFound();
		}
		return View(auditLog);
	}

	[HttpPost]
	[ValidateAntiForgeryToken]
	public ActionResult Edit(string id, string Comments)
	{
		DataViewer.EditAuditLog(_connectionString, id, Comments);
		return RedirectToAction("Index");
	}

	public ActionResult Delete(int? id)
	{
		if (!id.HasValue)
		{
			return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
		}
		AuditLog auditLog = db.AuditLogs.Find(id);
		if (auditLog == null)
		{
			return HttpNotFound();
		}
		return View(auditLog);
	}

	[HttpPost]
	[ActionName("Delete")]
	[ValidateAntiForgeryToken]
	public ActionResult DeleteConfirmed(int id)
	{
		AuditLog auditLog = db.AuditLogs.Find(id);
		db.AuditLogs.Remove(auditLog);
		db.SaveChanges();
		return RedirectToAction("Index");
	}

	protected override void Dispose(bool disposing)
	{
		if (disposing)
		{
			db.Dispose();
		}
		base.Dispose(disposing);
	}
}

BSMWeb/Views/AuditLogs/Create.cshtml
@model BSMWeb.Models.AuditLog

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MasterPages/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AuditLog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuditDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuditDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuditDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActionTaken, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActionTaken, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActionTaken, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BSMWeb/Views/AuditLogs/Delete.cshtml
@model BSMWeb.Models.AuditLog

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/MasterPages/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AuditLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReviewerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuditDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuditDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActionTaken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionTaken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BSMWeb/Views/AuditLogs/Details.cshtml
@model BSMWeb.Models.AuditLog

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/MasterPages/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AuditLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReviewerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuditDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuditDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActionTaken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActionTaken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AuditLogId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BSMWeb/Views/AuditLogs/Edit.cshtml
@model BSMWeb.Models.AuditLog

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/MasterPages/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<section id="main-content">
    <section class="wrapper site-min-height">
        <h3>
            Audit Log
        </h3>
        <hr />
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="title">
                            Edit Audit Log
                        </h4>
                    </div>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            <h4>AuditLog</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.AuditLogId)

                            <div class="form-group">
                                @Html.LabelFor(model => model.ReviewerName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DisplayTextFor(model => model.ReviewerName)
                                    @Html.ValidationMessageFor(model => model.ReviewerName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.AuditDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DisplayTextFor(model => model.AuditDate)
                                    @Html.ValidationMessageFor(model => model.AuditDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ActionTaken, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DisplayTextFor(model => model.ActionTaken)
                                    @Html.ValidationMessageFor(model => model.ActionTaken, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                            <div>
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>
}

BSMWeb/Views/AuditLogs/Index.cshtml
@using System.Data
@model DataSet
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MasterPages/_Layout.cshtml";
}

@section PageStyle {
    @*You can add your custom style sheets for each page on this section.*@
    <link rel="stylesheet" href="http://cdn.datatables.net/plug-ins/725b2a2115b/integration/bootstrap/3/dataTables.bootstrap.css" />
    <link href="~/Content/StyleSheets/jquery-ui.min.css" rel="stylesheet" />
}
@section PageJavaScript{
    <script type="text/javascript" src="../Content/Scripts/plugins/dataTables/jquery.dataTables.js"></script>
    <script type="text/javascript" src="http://cdn.datatables.net/plug-ins/725b2a2115b/integration/bootstrap/3/dataTables.bootstrap.js"></script>
    @*<script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                "order": [[0, "desc"]],
                "lengthMenu": [[100, 50, 25, 10, -1], [100, 50, 25, 10, "All"]]
            });
        });
    </script>*@
    <script src="~/Content/Scripts/jquery-ui.min.js"></script>
    <script type="text/javascript">
        $(function () {
            // This will make every element with the class "date-picker" into a DatePicker element
            $('.date-picker').datepicker({ dateFormat: 'dd/mm/yy' });
        })
    </script>


}
<section id="main-content">
    <section class="wrapper site-min-height">
        <h3>
            Audit Log
        </h3>
        <hr />
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        @using (Html.BeginForm("Index", "AuditLogs", FormMethod.Post))
                        {
                            <label>Enter Reviewer Name:</label>
                            <input name="reviewerName" />
                            <label>Select Audit Date:</label>
                            <input class="date-picker" id="auditDate" name="auditDate" autocomplete="off" />
                            <button name="Button">Search</button>
                        }
                    </div>
                    @using (Html.BeginForm("Index", "AuditLogs", FormMethod.Get))
                    {
                        <div class="panel-body">
                            <div class="table-responsive">

                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th>
                                                Reviewer Name
                                            </th>
                                            <th>
                                                Audit Date
                                            </th>
                                            <th>
                                                Action Taken
                                            </th>
                                            <th>
                                                Comments
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.Tables.Count > 0)
                                        {
                                            foreach (DataRow row in Model.Tables[0].Rows)
                                            {
                                                <tr class="gradeU">
                                                    <td class="hidden">@row["AuditLogId"]</td>
                                                    <td>@row["ReviewerName"]</td>
                                                    <td>@row["AuditDate"]</td>
                                                    <td>@row["ActionTaken"]</td>
                                                    <td>@row["Comments"]</td>
                                                    <td>@Html.ActionLink("Edit", "Edit", new { id = row["AuditLogId"] })</td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <div>
                                @Html.ActionLink("Create", "Create")
                            </div>
                        </div>
                    }
                </div>

            </div>
        </div>
    </section>
</section>